### ISSUE TITLE
Extracting with PowerShell occasionally fails

### ISSUE THREAD

**Issue by chrismin13** [chrismin13/parsec-download-script#5]
```
powershell -command "Expand-Archive -Path '%temp%\Parsec\parsec.zip' -DestinationPath '%temp%\Parsec' -Force"
Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file
'C:\Users\s-cm229846\AppData\Local\Temp\Parsec\parsecd-150-92a.dll' because it is being used by another process."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1056
char:25
+ ... [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : IOException
```

Could consider reverting back to extracting with Windows Explorer instead.

**Comment by run2go** [comment]
The error message sounds like parsecd.exe (or another process) is already running and accessing the dll file.
Using the System.IO class from PowerShell, you could check all files inside %temp%/Parsec/ prior to the zip file extraction...
Though this sounds a little overkill.

Incase the reason lies elsewhere, are there any ways to reproduce the error you received?

**Comment by chrismin13** [comment]
I believe the issue might be caused by antivirus software, as the affected machines have Trend Micro Security installed.
